### ISSUE TITLE
Question about lib usage

### ISSUE THREAD

**Issue by jverdasca** [dniloash/Pywinter#3]
Can you explain why "field" parameter values (arrays) in V3dp and V2d objects need at least one array value, such as numpy.nan or numpy.inf? I can't find this information documented anywhere.
Why doesn't it work if I provide all the array values?
Is it possible to provide a dataset for use according to the examples in the documentation or for testing purposes?
Thanks!

**Comment by dniloash** [comment]
Hello
1. The field parameter its the array you want to write into the intermediate file, for example temperature or wind. You should not need nan or inf values.
2. Sorry, really I dont understand that question.
3. Of course, give some time, I am going to update the examples with files you can open and use for testing. For now, if you are trying to create something you could try to write zeros or ones field with right dimensions ( for example numpy.zeros([len(lats),len(lons)]) for V2d or  numpy.ones([len(plevs),len(lats),len(lons)]) in V3dp ), although this data will probably cause an error if you run the model.

**Comment by dniloash** [comment]
New short example with data is available in the examples folder, I hope to add more later.

**Comment by jverdasca** [comment]
![Captura de ecrã de 2020-11-02 10-00-01](https://user-images.githubusercontent.com/73713137/97855781-2ea30b80-1cf3-11eb-8455-6474336ad8a2.png)

I made this small example (for test purposes only), which I present in the image, and if I run like this I get error 
![Captura de ecrã de 2020-11-02 10-08-21](https://user-images.githubusercontent.com/73713137/97856219-eafcd180-1cf3-11eb-9d87-fc9b42bbfe4f.png)
But if I substitute any value of the tp2m arrays for numpy.nan the program runs successfully and the file is written. Why does the error occur if I supply all the values ​​of the matrix?

Thanks for your time and patience

**Comment by dniloash** [comment]
Ok you welcome, the real problem here is not related with nan or inf values, really it is because you are using integer values to build the matrix, if you include at least one float value (for example 8 -> 8.0), it will run successfully. 
This is related with the way numpy deals with types of data, in real cases it is unlikely to find a matrix of integer values, but in the future I will make sure to include some correction to deal with this.
Additionally, the model doesn't recognize NaN or InF, these values are later replaced by -1E30, that is the value by default for missing data in the model.
